### ISSUE TITLE
No windows nanoserver 1809 images available

### ISSUE THREAD

**Issue by esrahofstede** [docker-library/openjdk#293]
There are currently no windows nanoserver 1809 images available.
Nanoserver images are much smaller and faster than windows server core images. The nanoserver 1809 images are also much smaller than the nanoserver 2016 images.

The current nanoserver 2016 images [cannot be used ](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility) with the new windows server 2019 (unless in [hyperv mode](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container)).

**Comment by wglambert** [comment]
See https://github.com/docker-library/openjdk/issues/295#issuecomment-486407726
>The `nanoserver:sac2016` tag is the only one we were ever based on (the last tag that still contained Powershell and thus was possible for us to build a useful image off of)

**Comment by tianon** [comment]
Moving my notes from https://github.com/docker-library/openjdk/pull/291 over here:

> I did some experimentation with this, and I'd say it's now blocked on https://bugs.openjdk.java.net/browse/JDK-8218486 / https://bugs.openjdk.java.net/browse/JDK-8225425 (which I ran into immediately after getting an image with Java in it).
>
> ---
>
> I got it on OpenJDK 8, 11, 13, etc (version doesn't matter -- it seems OpenJDK doesn't actually support Nano Server):
> 
> ```
> Launching JShell execution engine threw: C:\openjdk-13\bin\net.dll: Can't find dependent libraries
> ```
>
> ---
>
> If anyone wants to play with where I left off, my changes are pushed to https://github.com/docker-library/openjdk/compare/master...infosiftr:nanoserver

**Comment by slide** [comment]
@tianon That should be fixed in 8u232, which was just released.

**Comment by slide** [comment]
@wglambert Would basing the image off the powershell core nanoserver image (https://hub.docker.com/_/microsoft-powershell tags: nanoserver-1803, nanoserver-1809 and nanoserver-1903) work? It would provide a base image with pwsh.exe and the openjdk.

**Comment by tianon** [comment]
8: no jshell but `java -version` works fine :sweat_smile:
11: (likely harmless) jshell backspace error (below)
13: works
14: works

---

```console
jshell> a[backspace]
Exception in thread "main" java.lang.NullPointerException: charsetName
        at java.base/java.lang.String.<init>(String.java:464)
        at java.base/java.lang.String.<init>(String.java:537)
        at jdk.internal.le/jdk.internal.jline.extra.AnsiInterpretingOutputStream.write(AnsiInterpretingOutputStream.java:92) 
        at java.base/java.io.OutputStream.write(OutputStream.java:157)
        at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
        at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
        at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:316)
        at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
        at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:254)
        at jdk.internal.le/jdk.internal.jline.console.ConsoleReader.flush(ConsoleReader.java:1052)
        at jdk.internal.le/jdk.internal.jline.console.ConsoleReader.readLine(ConsoleReader.java:3259)
        at jdk.internal.le/jdk.internal.jline.console.ConsoleReader.readLine(ConsoleReader.java:2383)
        at jdk.internal.le/jdk.internal.jline.console.ConsoleReader.readLine(ConsoleReader.java:2371)
        at jdk.jshell/jdk.internal.jshell.tool.ConsoleIOContext.readLine(ConsoleIOContext.java:142) 
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.getInput(JShellTool.java:1261)
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.run(JShellTool.java:1174)
        at jdk.jshell/jdk.internal.jshell.tool.JShellTool.start(JShellTool.java:975)
        at jdk.jshell/jdk.internal.jshell.tool.JShellToolBuilder.start(JShellToolBuilder.java:254)
        at jdk.jshell/jdk.internal.jshell.tool.JShellToolProvider.main(JShellToolProvider.java:120)
```

---

I've force-pushed to my old branch with updated code (https://github.com/docker-library/openjdk/compare/master...infosiftr:nanoserver) and plan to open a PR shortly. :+1:

**Comment by tianon** [comment]
Doh wait, Travis is the bit that we've not resolved yet.  Just adding these to the Travis build matrix as-is won't work; we need to get a little more clever and build them semi-opportunistically alongside their Windows Server counterparts.
